### ISSUE TITLE
[paragraph detection] provide selection augmentation

### ISSUE THREAD

**Issue by schloett** [EEXCESS/c4#14]
Integrate a function, which allows to augment selections in a page with EEXCESS interactions (add keyword, set as paragraph, retrieve results for selection), like sketched in this screenshot:
![selection2](https://cloud.githubusercontent.com/assets/4618499/10903708/f32fea7c-820c-11e5-944b-2e1593190255.PNG)
It must be possible to turn the augmentation on and off.
For `add keyword` and `retrieve results for selection` I would propose to require custom function as parameters, which receive the corresponding values and `set as paragraph` might trigger an appropriate event. Hence the sketch for calling this function might look like so:

``` javascript
function augmentSelection(
  function(keywordToAdd) {
    // e.g. add to searchbar
  },
  function(selectedText) {
    // e.g. call paragraphToQuery and set keywords in searchBar
  }
);
```

**Comment by schloett** [comment]
additionally, keywords might be added by double-click. But this is probably functionality which needs to be implemented by the respective client, nevertheless, the search bar should provide a function to add keywords, which the client can then call. For the chrome-extension, a separate issue https://github.com/EEXCESS/chrome-extension/issues/37 has been created.

**Comment by treml05** [comment]
The plan is that 3 different buttons appear on the right-side of the selection.

B1.: "Add these words as a Keyword-Tag in the SearchBar"
B2.: "Search with the (automatically recognised) Named Entities in this selection"
B3.: "Handle this selection as a paragraph"

**Comment by treml05** [comment]
Buttons:
![screenshot 2015-11-05 19 40 59](https://cloud.githubusercontent.com/assets/12858754/10978130/9ba551f8-83f5-11e5-9670-924be0e125ee.png)

**Comment by treml05** [comment]
B1 & B2 are working good now.
Some Design & Usability improvements are in progress now.
Furthermore I'm working on a good solution for B3.
(What happens, if the selection is shorter than one paragraph, or the selection is part of 2 or more paragraphs...)

**Comment by schloett** [comment]
We might add a 4th button, which allows the user to set the selection as main topic. This makes only sense, if the selection is short, basically a keyword in itself. Not sure, if we should provide the main topic option only if that is the case or for consistency everytime.

**Comment by treml05** [comment]
Ok, I undersand.
Any proposal for a button-design? There should be a "design-consistency" in terms of main topics.
About your question: Perhaps it's a good solution if the button isn't grey, if the selection is too long?

I'll think about this.

**Comment by schloett** [comment]
The 4th button is not the focus currently, first things first ;) I just wanted to mention it here, in order not to forget. But first the other buttons need to work and there must be the possibility to switch the augmentation off again.

**Comment by treml05** [comment]
augmentation can be switched on/off.
first three buttons work. (in my opinion)

**Comment by treml05** [comment]
Improvement, we discussed today:

-show 3rd GREEN button just in case the selection makes sense. (tooltip: description ->make paragraph)
-if selection doesn't make sense: show GREY button without function (tooltip: selection doesn't make sense)

**Comment by treml05** [comment]
Suggestion for Button 4:

![screenshot 2015-12-15 17 46 28](https://cloud.githubusercontent.com/assets/12858754/11817126/ddba6ea2-a353-11e5-9f5b-2ecd48c3831d.png)

**Comment by schloett** [comment]
looks nice. Maybe you could move the line in the middle a bit to the bottom? Such that it resembles the main topic UI element a bit more?
![mt](https://cloud.githubusercontent.com/assets/4618499/11818044/644d1538-a358-11e5-9d3e-6d784c0a7e46.PNG)

**Comment by treml05** [comment]
First version with all discussed topics is online.
- 4 buttons
- button 4 just works if selection is long enough (design improved)
- button 3 just works if selection makes sense

problems atm:
button 3 is not performant
don't know the best solution to add a mainTopic

**Comment by schloett** [comment]
Could you please provide some documentation on the code for the 4th button and wrap the parameters of `activateSelectionAugmentation` in an object with optional arguments as discussed last time?
Also, you might need to consider the position in addition to the width. For example, in a setting like this:

```
---
  ---
---
```

each "paragraph" has the same width, but the bounding box is larger.
Regarding the problems:
- I did not notice a lag for button 3 (did not test extensively), if there really is no noticeable lag, I would consider it sufficient for the time being.
- Just pass the selection as parameter to the function provided in the arguments of `activateSelectionAugmentation`, it's up to the provider of this function to handle it correctly. (not sure if the searchBar exposes the ability to set the main topic externally yet).

**Comment by treml05** [comment]
you're right. Button 3 works well! 

made now all improvements, you said and it still works fine. 

but still cannot handle to set mainTopics..

**Comment by schloett** [comment]
No problem with the main topic, just pass the selection to the function as with the other options. In addition, you may assign me an issue for adding a main topic to the search bar (then you will get notified when the issue is fixed and you can integrate it in the example - code is already available, did not have the time to push it in the master branch yet). Also there is an improvement and a bugfix to add, but I will create separate issues for it
