### ISSUE TITLE
[Paragraph Detection] fails on twitter (when logged in)

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/c4#21]
The following funny keywords are extracted on a Twitter page (https://twitter.com/eexcess)
IF the user is LOGGED IN

![image001](https://cloud.githubusercontent.com/assets/4638470/11267382/5ddc5748-8eab-11e5-82ef-6edded0fbc11.png)

The html code of the page (IF logged in) is attached 
[twitter_html.txt](https://github.com/EEXCESS/c4/files/38806/twitter_html.txt)

**Comment by schloett** [comment]
What's so funny about these keywords? ;)
![twitter](https://cloud.githubusercontent.com/assets/4618499/11272515/c9f9c66e-8ecd-11e5-8867-d9665b7e661c.png)
Checking for visibility unfortunately is a real performance killer. I've integrated a version into c4 which seems acceptable in terms of computing time (~ up to 200ms, only tested with a few pages), but is not perfectly accurate (works fine for the provided twitter example). Checking for visibility can be switched off by passing the corresponding options parameter to the paragraphDetection method. 
Some numbers to get an intuition:
~20ms without check for visibility
~200ms with current implementation
~2000ms with in-depth check 
(still the last one does not capture opacity or similar)

**Comment by schloett** [comment]
@chseifert could you check if this issue is fixed and if yes close it?

**Comment by chseifert** [comment]
Reactivated my twitter account and checked. Works :)
