### ISSUE TITLE
license information for c4 files

### ISSUE THREAD

**Issue by gdoppler** [EEXCESS/c4#30]
For acceptance of or moodle plugin we will need to provide license information for all third-party files that we use, e.g. APIConnector.js from c4. 
We should provide the licenses for all these files in a structure like
<?xml version="1.0"?>
<libraries>
    <library>
        <location>javascript/html5shiv.js</location>
        <name>Html5Shiv</name>
        <version>3.6.2</version>
        <license>Apache</license>
        <licenseversion>2.0</licenseversion>
    </library>
    <library>
        <location>vendor/guzzle/guzzle/</location>
        <name>guzzle</name>
        <version>v3.9.3</version>
        <license>MIT</license>
        <licenseversion></licenseversion>
    </library>
</libraries>

So we would need version and license information. Have we agreed on license for c4?
For being used in Moodle that license must be compatible with the GNU GPLv3. 
http://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses

**Comment by schloett** [comment]
version and license information is available in `bower.json`. (latest version: 6.5.2, license: MIT).
